script:
  - cd ..
  - git clone "https://github.com/qz757/qz757.github.com.git"
  - cd qz757.github.com
  - git config user.name "CI"
  - git config user.email "qz757@sina.com"
  - cp ../blogdata/*.md source/_posts/
  - git add -A
  - git commit -m "auto publish"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/qz757/qz757.github.com.git" hexo:hexo

branches:
  only:
    - master